In [1]:
import os 
os.listdir()

['.ipynb_checkpoints',
 'Adding and Updating Dataframes.ipynb',
 'Dropping Columns and Rows in a Dataframe.ipynb',
 'Image Processing using Numpy.ipynb',
 'Indexing and Slicing Dataframes.ipynb',
 'Indexing, Slicing and Iterating.ipynb',
 'Loading Files into Pandas DataFrame.ipynb',
 'NewImage.png',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testing.ipynb',
 'Using Geopy.ipynb']

In [5]:
import cv2
img = cv2.imread("smallgray.png" , 0)

In [6]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
img[0:2] #Slicing the numpy array row wise

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [8]:
img[0:2 , 2:4] #Slicing the numpy array row wise first and then column wise. The first argument is passing the row indexes and 
                #the second argument is passing the column indexes.

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
img[2,4] #Slicing the numpy array by the exact value. The first argument is the row value and the second is the column value.

182

In [10]:
for value in img: #value is the iterator which iterates through all the values in the numpy array one by one row wise.
                    #Same can be done for column wise iteration by transposing the numpy array.
    print(value)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [11]:
for value in img.T: #value is the iterator which iterates through all the values in the numpy array one by one column wise 
                    #(Row wise to be precise. It's just that we have transposed the numpy array).
                    #Same can be done for row wise iteration by taking the numpy array as it is.
    print(value)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [12]:
for value in img.flat: #numpy_array.flat attribute allows us to access each element of the array one by one without row or
                        #column constraints.
    print(value)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
