In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Adding and Updating Dataframes.ipynb',
 'Dropping Columns and Rows in a Dataframe.ipynb',
 'Image Processing using Numpy.ipynb',
 'Indexing and Slicing Dataframes.ipynb',
 'Indexing, Slicing and Iterating.ipynb',
 'Loading Files into Pandas DataFrame.ipynb',
 'NewImage.png',
 'smallgray.png',
 'Stacking and Splitting.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testing.ipynb',
 'Using Geopy.ipynb']

In [4]:
import cv2
img = cv2.imread("smallgray.png" , 0)

In [5]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
import numpy
bigArray = numpy.hstack((img,img)) #hstack is for horizontal stacking i.e adding one numpy at the end of other in the horizontal
                                    #direction. numpy.hstack() takes only one positional parameters as input and thus we pass
                                    #two numpy arrays as a tuple to the method. If we pass it as numpy.hstack(img,img), we get
                                    #an error as TypeError: hstack() takes 1 positional argument but 2 were given.

In [8]:
bigArray

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
bigArray1 = numpy.vstack((img,img)) #vstack is similar to the hstack method but this concatenates two numpy arrays in the
                                    #vertical direction.

In [12]:
bigArray1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
print(type(bigArray1))
print(type(bigArray))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
splitArray = numpy.hsplit(bigArray,2) #Opposite to what hstack does, hsplit() splits the input array (bigArray) into the number
                                        #of arrays as specified by the second argument. 

In [14]:
splitArray

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [15]:
print(type(splitArray))

<class 'list'>


In [16]:
print(splitArray[0])
print(splitArray[1])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [17]:
splitArray = numpy.hsplit(bigArray,5)

In [18]:
print(splitArray)

[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]


In [19]:
for value in range(0,5):
    print(splitArray[value])

[[187 158]
 [198 125]
 [209 134]]
[[104 121]
 [255 255]
 [255  97]]
[[143 187]
 [147 198]
 [182 209]]
[[158 104]
 [125 255]
 [134 255]]
[[121 143]
 [255 147]
 [ 97 182]]


In [20]:
vsplitArray = numpy.vsplit(bigArray1,2) #Opposite to what vstack does, vsplit() splits the input array (bigArray1) into the 
                                        #number of arrays as specified by the second argument.

In [21]:
print(type(vsplitArray))

<class 'list'>


In [22]:
print(vsplitArray[0])
print(vsplitArray[1])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [23]:
vsplitArray = numpy.vsplit(bigArray1,3)

In [24]:
vsplitArray

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [25]:
for value in range(0,3):
    print(vsplitArray[value])

[[187 158 104 121 143]
 [198 125 255 255 147]]
[[209 134 255  97 182]
 [187 158 104 121 143]]
[[198 125 255 255 147]
 [209 134 255  97 182]]
